# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Keep window name
set-option -g allow-rename off  

# Create panel in current path
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Enable mouse
set -g mouse on

# Enable activity alerts
# set -g monitor-activity on
# set -g visual-activity on

# Navigate using Vim shortcuts
# setw -g mode-keys vi

# soften status bar color from harsh green to light gray
set -g status-style bg='#666666',fg='#aaaaaa'
