# Keep window name
set-option -g allow-rename off  

# Create panel in current path
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Enable activity alerts
set -g monitor-activity on
set -g visual-activity on

# Navigate using Vim shortcuts
setw -g mode-keys vi

# Enable mouse
set -g mouse on
